### ISSUE TITLE
Support for platform specific extension breaks "directories as modules"

### ISSUE THREAD

**Issue by pierre-elie** [kristerkari/react-native-sass-transformer#17] opened 2018-10-29 23:00 UTC
Consider the following file hierarchy

<img width="642" alt="capture d ecran 2018-10-29 a 18 55 56" src="https://user-images.githubusercontent.com/5923751/47685272-4ac3bd80-dbac-11e8-9a57-c57c9ecdedb0.png">

Prior to version 1.3.0, `@import "uikit/style/common"` was correctly resolved, consistent with the node.js resolution: `uikit-lib` was considered like a module named `uikit` because of its package.json.

In version 1.3.0, import paths do not include the correct "node.js" resolution of `uikit`.

(Including `package.json` in directories other than real modules is useful to avoid relative paths and for Git submodules)

Thanks!

**Comment by kristerkari** [comment] 2018-10-30 07:13
Thanks @pierre-elie! I did not even know about this feature.

Would it be possible for you to setup a repository where the issue can be reproduced? That way it would be a lot easier to work on a fix for this.

**Comment by pierre-elie** [comment] 2018-10-30 22:14
I'll do that, thanks!

**Closed** 2018-11-01 18:32 UTC
Labels: bug

**Comment by kristerkari** [comment] 2018-11-01 18:38
@pierre-elie I managed to to reproduce the issue and fix it. Please test v1.3.1 and let me know if the issue is now fixed. :)

**Comment by pierre-elie** [comment] 2018-11-03 22:43
I confirmed it's fixed with 1.3.1, thanks a lot 👍

**Comment by kristerkari** [comment] 2018-11-04 07:31
Great! Please let me know if you find something else that is not working :)
